apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.service.name }} 
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}" 
    visualize: "true" 
    app: {{ .Values.service.name }} 
spec:
  replicas: {{ .Values.replicaCount }} 
  selector: 
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true" 
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.service.name }}
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .Values.service.name }} 
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: APP_PORT
          value: "8080"
        - name: APP_NAME
          value: {{ .Values.service.name }}
        - name: HANDLER_PATH
          value: {{ .Values.env.HANDLER_PATH }}
        - name: CONTENT_SOURCE_URI
          value: {{ .Values.env.CONTENT_SOURCE_URI }}
        - name: INTERNAL_COMPONENTS_SOURCE_URI
          value: {{ .Values.env.INTERNAL_COMPONENTS_SOURCE_URI }}
        - name: CONTENT_SOURCE_APP_HEALTH_URI
          value: {{ .Values.env.CONTENT_SOURCE_APP_HEALTH_URI }}
        - name: INTERNAL_COMPONENTS_SOURCE_APP_HEALTH_URI
          value: {{ .Values.env.INTERNAL_COMPONENTS_SOURCE_APP_HEALTH_URI }}
        - name: CONTENT_SOURCE_APP_NAME
          value: {{ .Values.env.CONTENT_SOURCE_APP_NAME }}
        - name: INTERNAL_COMPONENTS_SOURCE_APP_NAME
          value: {{ .Values.env.INTERNAL_COMPONENTS_SOURCE_APP_NAME }}
        - name: CONTENT_SOURCE_APP_PANIC_GUIDE
          value: {{ .Values.env.CONTENT_SOURCE_APP_PANIC_GUIDE }}
        - name: INTERNAL_COMPONENTS_SOURCE_APP_PANIC_GUIDE
          value: {{ .Values.env.INTERNAL_COMPONENTS_SOURCE_APP_PANIC_GUIDE }}
        - name: CONTENT_SOURCE_APP_BUSINESS_IMPACT
          value: {{ .Values.env.CONTENT_SOURCE_APP_BUSINESS_IMPACT }}
        - name: INTERNAL_COMPONENTS_SOURCE_APP_BUSINESS_IMPACT
          value: {{ .Values.env.INTERNAL_COMPONENTS_SOURCE_APP_BUSINESS_IMPACT }}
        - name: CONTENT_UNROLLER_URI
          value: {{ .Values.env.CONTENT_UNROLLER_URI }}
        - name: CONTENT_UNROLLER_APP_NAME
          value: {{ .Values.env.CONTENT_UNROLLER_APP_NAME }}
        - name: CONTENT_UNROLLER_APP_HEALTH_URI
          value: {{ .Values.env.CONTENT_UNROLLER_APP_HEALTH_URI }}
        - name: CONTENT_UNROLLER_APP_PANIC_GUIDE
          value: {{ .Values.env.CONTENT_UNROLLER_APP_PANIC_GUIDE }}
        - name: CONTENT_UNROLLER_APP_BUSINESS_IMPACT
          value: {{ .Values.env.CONTENT_UNROLLER_APP_BUSINESS_IMPACT }}
        - name: APP_SYSTEM_CODE
          value: {{ .Values.env.APP_SYSTEM_CODE }}
        - name: ENV_API_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: api.host
        - name: CACHE_CONTROL_POLICY
          value: {{ .Values.env.CACHE_CONTROL_POLICY }}
        - name: GRAPHITE_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: graphite.address
        - name: GRAPHITE_PREFIX
          value: "coco.services.k8s.{{ .Values.service.name }}"
        ports: 
        - containerPort: 8080
        livenessProbe: 
          tcpSocket: 
            port: 8080 
          initialDelaySeconds: 10 
        readinessProbe: 
          httpGet: 
            path: "/__gtg" 
            port: 8080 
          initialDelaySeconds: 15 
          periodSeconds: 30 
        resources: 
{{ toYaml .Values.resources | indent 12 }}

